#!/usr/bin/env python
import os
import argparse

parser = argparse.ArgumentParser()
   
parser.add_argument('-d', '--ip', '--dest', dest='ip', required=True, 
    help="destination ip address")

args = parser.parse_args()

os.system('scp MaixPy3/files/etc/banner root@192.168.1.76:/etc')
os.system('scp MaixPy3/files/etc/hostname root@192.168.1.76:/etc')
# os.system('scp -rp ./occi/occi root@192.168.1.76:/home')
os.system('scp -rp ./occi_demo_resnet root@192.168.1.76:/usr/share/occi/occi_demo_resnet')
os.system('scp -rp ./occi_default root@192.168.1.76:/usr/share/occi/occi_default')
os.system('scp -rp ./occi_movement root@192.168.1.76:/usr/share/occi/occi_movement')
os.system('scp -rp ./occi_seeing root@192.168.1.76:/usr/share/occi/occi_seeing')
os.system('scp -rp ./occi_training root@192.168.1.76:/usr/share/occi/occi_training')

os.system('scp -rp ./subcognition/camera/dist/* root@192.168.1.76:/root/maix_dist')
os.system('scp -rp ./MaixPy3/files/usr/bin/* root@192.168.1.76:/usr/bin')

os.system('scp -rp ./occi/occi root:"turkey is for dinner"@{}:/usr/lib/python3.8/site-packages'.format(args.ip))
os.system('scp -rp ./docker/occi-0.1.dist-info root:"turkey is for dinner"@{}:/usr/lib/python3.8/site-packages'.format(args.ip))
os.system('scp -rp ./MaixPy3/home root:"turkey is for dinner"@{}:/home'.format(args.ip))
