name: docker-github-actions
on: [push]
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
  container_custom:
    runs-on: ubuntu-latest
    container: alexlyrakis/alpine_opencv_toolchain@sha256:c085aa114af0
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          uname -m
        name: Run in container
  