name: Rust

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: 
    - ubuntu-latest
    - macOS
    - Linux

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
